var qbData = [
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': '@', 'opponent': 'DAL', 'Price': 'n/a', 'Proj': '21.8', 'adjPF': '23.7', 'adjPA': '19.4'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'home_away': '@', 'opponent': 'HOU', 'Price': 'n/a', 'Proj': '21.5', 'adjPF': '20.4', 'adjPA': '22.9'},
{'quarterback': 'Alex Smith', 'team': 'KCC', 'home_away': 'vs.', 'opponent': 'MIA', 'Price': 'n/a', 'Proj': '20.6', 'adjPF': '21.7', 'adjPA': '19.2'},
{'quarterback': 'Cam Newton', 'team': 'CAR', 'home_away': 'vs.', 'opponent': 'TBB', 'Price': 'n/a', 'Proj': '20.3', 'adjPF': '21.1', 'adjPA': '19.4'},
{'quarterback': 'Case Keenum', 'team': 'MIN', 'home_away': '@', 'opponent': 'GBP', 'Price': 'n/a', 'Proj': '20.3', 'adjPF': '19.7', 'adjPA': '21'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'home_away': '@', 'opponent': 'NYJ', 'Price': 'n/a', 'Proj': '20', 'adjPF': '18', 'adjPA': '22.3'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'home_away': '@', 'opponent': 'CIN', 'Price': 'n/a', 'Proj': '19.8', 'adjPF': '20.8', 'adjPA': '18.7'},
{'quarterback': 'Nick Foles', 'team': 'PHI', 'home_away': 'vs.', 'opponent': 'OAK', 'Price': 'n/a', 'Proj': '18.8', 'adjPF': '18.2', 'adjPA': '19.6'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'home_away': '@', 'opponent': 'TEN', 'Price': 'n/a', 'Proj': '18.8', 'adjPF': '18', 'adjPA': '19.7'},
{'quarterback': 'Kirk Cousins', 'team': 'WAS', 'home_away': 'vs.', 'opponent': 'DEN', 'Price': 'n/a', 'Proj': '18.7', 'adjPF': '20.1', 'adjPA': '17.1'},
{'quarterback': 'Drew Brees', 'team': 'NOS', 'home_away': 'vs.', 'opponent': 'ATL', 'Price': 'n/a', 'Proj': '18.7', 'adjPF': '18.9', 'adjPA': '18.5'},
{'quarterback': 'Tyrod Taylor', 'team': 'BUF', 'home_away': '@', 'opponent': 'NEP', 'Price': 'n/a', 'Proj': '18.6', 'adjPF': '17.1', 'adjPA': '20.3'},
{'quarterback': 'Jameis Winston', 'team': 'TBB', 'home_away': '@', 'opponent': 'CAR', 'Price': 'n/a', 'Proj': '18.4', 'adjPF': '19.2', 'adjPA': '17.3'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'home_away': '@', 'opponent': 'SFF', 'Price': 'n/a', 'Proj': '18.3', 'adjPF': '17.4', 'adjPA': '19.4'},
{'quarterback': 'Tom Brady', 'team': 'NEP', 'home_away': 'vs.', 'opponent': 'BUF', 'Price': 'n/a', 'Proj': '17.7', 'adjPF': '21.5', 'adjPA': '13'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'home_away': 'vs.', 'opponent': 'DET', 'Price': 'n/a', 'Proj': '17.5', 'adjPF': '16.5', 'adjPA': '18.9'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'SEA', 'Price': 'n/a', 'Proj': '17.2', 'adjPF': '18.1', 'adjPA': '16.1'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'home_away': '@', 'opponent': 'PHI', 'Price': 'n/a', 'Proj': '16.9', 'adjPF': '16.6', 'adjPA': '17.3'},
{'quarterback': 'Mitch Trubisky', 'team': 'CHI', 'home_away': 'vs.', 'opponent': 'CLE', 'Price': 'n/a', 'Proj': '16.7', 'adjPF': '11.9', 'adjPA': '22.6'},
{'quarterback': 'T.J. Yates', 'team': 'HOU', 'home_away': 'vs.', 'opponent': 'PIT', 'Price': 'n/a', 'Proj': '16.5', 'adjPF': '17.1', 'adjPA': '15.9'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': '@', 'opponent': 'ARI', 'Price': 'n/a', 'Proj': '16.5', 'adjPF': '15.3', 'adjPA': '18'},
{'quarterback': 'Drew Stanton', 'team': 'ARI', 'home_away': 'vs.', 'opponent': 'NYG', 'Price': 'n/a', 'Proj': '16.3', 'adjPF': '13.1', 'adjPA': '20.1'},
{'quarterback': 'Brock Osweiler', 'team': 'DEN', 'home_away': '@', 'opponent': 'WAS', 'Price': 'n/a', 'Proj': '16', 'adjPF': '15.6', 'adjPA': '16.6'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'home_away': '@', 'opponent': 'NOS', 'Price': 'n/a', 'Proj': '15.9', 'adjPF': '15.6', 'adjPA': '16.2'},
{'quarterback': 'Jay Cutler', 'team': 'MIA', 'home_away': '@', 'opponent': 'KCC', 'Price': 'n/a', 'Proj': '15.8', 'adjPF': '14.1', 'adjPA': '17.8'},
{'quarterback': 'Joe Flacco', 'team': 'BAL', 'home_away': 'vs.', 'opponent': 'IND', 'Price': 'n/a', 'Proj': '15.8', 'adjPF': '12.2', 'adjPA': '20.1'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'home_away': 'vs.', 'opponent': 'LAR', 'Price': 'n/a', 'Proj': '15', 'adjPF': '15.2', 'adjPA': '14.8'},
{'quarterback': 'DeShone Kizer', 'team': 'CLE', 'home_away': '@', 'opponent': 'CHI', 'Price': 'n/a', 'Proj': '15', 'adjPF': '15.4', 'adjPA': '14.6'},
{'quarterback': 'Brett Hundley', 'team': 'GBP', 'home_away': 'vs.', 'opponent': 'MIN', 'Price': 'n/a', 'Proj': '14.8', 'adjPF': '16', 'adjPA': '13.3'},
{'quarterback': 'Jacoby Brissett', 'team': 'IND', 'home_away': '@', 'opponent': 'BAL', 'Price': 'n/a', 'Proj': '14.2', 'adjPF': '15.8', 'adjPA': '12.3'},
{'quarterback': 'Jimmy Garoppolo', 'team': 'SFF', 'home_away': 'vs.', 'opponent': 'JAC', 'Price': 'n/a', 'Proj': '13.4', 'adjPF': '15.1', 'adjPA': '11.4'},
{'quarterback': 'Bryce Petty', 'team': 'NYJ', 'home_away': 'vs.', 'opponent': 'LAC', 'Price': 'n/a', 'Proj': '12.4', 'adjPF': '11.2', 'adjPA': '14'}
];

var matchups = [
'Russell Wilson (SEA @ DAL): 21.8 proj. pts.',
'Ben Roethlisberger (PIT @ HOU): 21.5 proj. pts.',
'Alex Smith (KCC vs. MIA): 20.6 proj. pts.',
'Cam Newton (CAR vs. TBB): 20.3 proj. pts.',
'Case Keenum (MIN @ GBP): 20.3 proj. pts.',
'Philip Rivers (LAC @ NYJ): 20 proj. pts.',
'Matthew Stafford (DET @ CIN): 19.8 proj. pts.',
'Nick Foles (PHI vs. OAK): 18.8 proj. pts.',
'Jared Goff (LAR @ TEN): 18.8 proj. pts.',
'Kirk Cousins (WAS vs. DEN): 18.7 proj. pts.',
'Drew Brees (NOS vs. ATL): 18.7 proj. pts.',
'Tyrod Taylor (BUF @ NEP): 18.6 proj. pts.',
'Jameis Winston (TBB @ CAR): 18.4 proj. pts.',
'Blake Bortles (JAC @ SFF): 18.3 proj. pts.',
'Tom Brady (NEP vs. BUF): 17.7 proj. pts.',
'Andy Dalton (CIN vs. DET): 17.5 proj. pts.',
'Dak Prescott (DAL vs. SEA): 17.2 proj. pts.',
'Derek Carr (OAK @ PHI): 16.9 proj. pts.',
'Mitch Trubisky (CHI vs. CLE): 16.7 proj. pts.',
'T.J. Yates (HOU vs. PIT): 16.5 proj. pts.',
'Eli Manning (NYG @ ARI): 16.5 proj. pts.',
'Drew Stanton (ARI vs. NYG): 16.3 proj. pts.',
'Brock Osweiler (DEN @ WAS): 16 proj. pts.',
'Matt Ryan (ATL @ NOS): 15.9 proj. pts.',
'Jay Cutler (MIA @ KCC): 15.8 proj. pts.',
'Joe Flacco (BAL vs. IND): 15.8 proj. pts.',
'Marcus Mariota (TEN vs. LAR): 15 proj. pts.',
'DeShone Kizer (CLE @ CHI): 15 proj. pts.',
'Brett Hundley (GBP vs. MIN): 14.8 proj. pts.',
'Jacoby Brissett (IND @ BAL): 14.2 proj. pts.',
'Jimmy Garoppolo (SFF vs. JAC): 13.4 proj. pts.',
'Bryce Petty (NYJ vs. LAC): 12.4 proj. pts.'
];


var fd1qbData = [
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': '@', 'opponent': 'DAL', 'Price': '9000', 'Proj': '20.6'},
{'quarterback': 'Tom Brady', 'team': 'NEP', 'home_away': 'vs.', 'opponent': 'BUF', 'Price': '8600', 'Proj': '17.1'},
{'quarterback': 'Drew Brees', 'team': 'NOS', 'home_away': 'vs.', 'opponent': 'ATL', 'Price': '8400', 'Proj': '17.7'},
{'quarterback': 'Cam Newton', 'team': 'CAR', 'home_away': 'vs.', 'opponent': 'TBB', 'Price': '8300', 'Proj': '19.7'},
{'quarterback': 'Case Keenum', 'team': 'MIN', 'home_away': '@', 'opponent': 'GBP', 'Price': '8200', 'Proj': '19.1'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'home_away': '@', 'opponent': 'NYJ', 'Price': '8100', 'Proj': '18.7'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'home_away': '@', 'opponent': 'CIN', 'Price': '7900', 'Proj': '18.6'},
{'quarterback': 'Alex Smith', 'team': 'KCC', 'home_away': 'vs.', 'opponent': 'MIA', 'Price': '7800', 'Proj': '19.3'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'home_away': '@', 'opponent': 'TEN', 'Price': '7700', 'Proj': '17.5'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'home_away': '@', 'opponent': 'NOS', 'Price': '7700', 'Proj': '15.5'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'SEA', 'Price': '7600', 'Proj': '16.7'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'home_away': '@', 'opponent': 'SFF', 'Price': '7600', 'Proj': '17.3'},
{'quarterback': 'Tyrod Taylor', 'team': 'BUF', 'home_away': '@', 'opponent': 'NEP', 'Price': '7500', 'Proj': '17.8'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'home_away': 'vs.', 'opponent': 'LAR', 'Price': '7500', 'Proj': '15'},
{'quarterback': 'Kirk Cousins', 'team': 'WAS', 'home_away': 'vs.', 'opponent': 'DEN', 'Price': '7300', 'Proj': '17.6'},
{'quarterback': 'Jameis Winston', 'team': 'TBB', 'home_away': '@', 'opponent': 'CAR', 'Price': '7100', 'Proj': '17.5'},
{'quarterback': 'Jimmy Garoppolo', 'team': 'SFF', 'home_away': 'vs.', 'opponent': 'JAC', 'Price': '7000', 'Proj': '13.6'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'home_away': 'vs.', 'opponent': 'DET', 'Price': '6900', 'Proj': '16.8'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': '@', 'opponent': 'ARI', 'Price': '6800', 'Proj': '15.9'},
{'quarterback': 'Mitch Trubisky', 'team': 'CHI', 'home_away': 'vs.', 'opponent': 'CLE', 'Price': '6800', 'Proj': '15.9'},
{'quarterback': 'Brock Osweiler', 'team': 'DEN', 'home_away': '@', 'opponent': 'WAS', 'Price': '6700', 'Proj': '15.8'},
{'quarterback': 'Jay Cutler', 'team': 'MIA', 'home_away': '@', 'opponent': 'KCC', 'Price': '6700', 'Proj': '15.5'},
{'quarterback': 'DeShone Kizer', 'team': 'CLE', 'home_away': '@', 'opponent': 'CHI', 'Price': '6600', 'Proj': '15.2'},
{'quarterback': 'Drew Stanton', 'team': 'ARI', 'home_away': 'vs.', 'opponent': 'NYG', 'Price': '6500', 'Proj': '15.5'},
{'quarterback': 'Bryce Petty', 'team': 'NYJ', 'home_away': 'vs.', 'opponent': 'LAC', 'Price': '6500', 'Proj': '12.5'},
{'quarterback': 'Brett Hundley', 'team': 'GBP', 'home_away': 'vs.', 'opponent': 'MIN', 'Price': '6000', 'Proj': '14.8'}
];

var fd1matchups = [
'Russell Wilson (SEA @ DAL): 20.6 proj. [$9000]',
'Tom Brady (NEP vs. BUF): 17.1 proj. [$8600]',
'Drew Brees (NOS vs. ATL): 17.7 proj. [$8400]',
'Cam Newton (CAR vs. TBB): 19.7 proj. [$8300]',
'Case Keenum (MIN @ GBP): 19.1 proj. [$8200]',
'Philip Rivers (LAC @ NYJ): 18.7 proj. [$8100]',
'Matthew Stafford (DET @ CIN): 18.6 proj. [$7900]',
'Alex Smith (KCC vs. MIA): 19.3 proj. [$7800]',
'Jared Goff (LAR @ TEN): 17.5 proj. [$7700]',
'Matt Ryan (ATL @ NOS): 15.5 proj. [$7700]',
'Dak Prescott (DAL vs. SEA): 16.7 proj. [$7600]',
'Blake Bortles (JAC @ SFF): 17.3 proj. [$7600]',
'Tyrod Taylor (BUF @ NEP): 17.8 proj. [$7500]',
'Marcus Mariota (TEN vs. LAR): 15 proj. [$7500]',
'Kirk Cousins (WAS vs. DEN): 17.6 proj. [$7300]',
'Jameis Winston (TBB @ CAR): 17.5 proj. [$7100]',
'Jimmy Garoppolo (SFF vs. JAC): 13.6 proj. [$7000]',
'Andy Dalton (CIN vs. DET): 16.8 proj. [$6900]',
'Eli Manning (NYG @ ARI): 15.9 proj. [$6800]',
'Mitch Trubisky (CHI vs. CLE): 15.9 proj. [$6800]',
'Brock Osweiler (DEN @ WAS): 15.8 proj. [$6700]',
'Jay Cutler (MIA @ KCC): 15.5 proj. [$6700]',
'DeShone Kizer (CLE @ CHI): 15.2 proj. [$6600]',
'Drew Stanton (ARI vs. NYG): 15.5 proj. [$6500]',
'Bryce Petty (NYJ vs. LAC): 12.5 proj. [$6500]',
'Brett Hundley (GBP vs. MIN): 14.8 proj. [$6000]'
];


var fd2qbData = [
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': '@', 'opponent': 'DAL', 'Price': '9900', 'Proj': '20.6'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'home_away': '@', 'opponent': 'HOU', 'Price': '9100', 'Proj': '20.2'},
{'quarterback': 'Nick Foles', 'team': 'PHI', 'home_away': 'vs.', 'opponent': 'OAK', 'Price': '8400', 'Proj': '17.7'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'SEA', 'Price': '8300', 'Proj': '16.7'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'home_away': '@', 'opponent': 'PHI', 'Price': '7900', 'Proj': '16.4'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': '@', 'opponent': 'ARI', 'Price': '7300', 'Proj': '15.9'},
{'quarterback': 'T.J. Yates', 'team': 'HOU', 'home_away': 'vs.', 'opponent': 'PIT', 'Price': '6700', 'Proj': '15.7'},
{'quarterback': 'Drew Stanton', 'team': 'ARI', 'home_away': 'vs.', 'opponent': 'NYG', 'Price': '6500', 'Proj': '15.5'}
];

var fd2matchups = [
'Russell Wilson (SEA @ DAL): 20.6 proj. [$9900]',
'Ben Roethlisberger (PIT @ HOU): 20.2 proj. [$9100]',
'Nick Foles (PHI vs. OAK): 17.7 proj. [$8400]',
'Dak Prescott (DAL vs. SEA): 16.7 proj. [$8300]',
'Derek Carr (OAK @ PHI): 16.4 proj. [$7900]',
'Eli Manning (NYG @ ARI): 15.9 proj. [$7300]',
'T.J. Yates (HOU vs. PIT): 15.7 proj. [$6700]',
'Drew Stanton (ARI vs. NYG): 15.5 proj. [$6500]'
];