var qbData = [
{'quarterback': 'Jacoby Brissett', 'team': 'IND', 'home_away': '@', 'opponent': 'BAL', 'adjPF': '15.8', 'adjPA': '12.3', 'Proj': '14.2'},
{'quarterback': 'Joe Flacco', 'team': 'BAL', 'home_away': 'vs.', 'opponent': 'IND', 'adjPF': '12.2', 'adjPA': '20.1', 'Proj': '15.8'},
{'quarterback': 'Case Keenum', 'team': 'MIN', 'home_away': '@', 'opponent': 'GBP', 'adjPF': '19.7', 'adjPA': '21', 'Proj': '20.3'},
{'quarterback': 'Brett Hundley', 'team': 'GBP', 'home_away': 'vs.', 'opponent': 'MIN', 'adjPF': '16', 'adjPA': '13.3', 'Proj': '14.8'},
{'quarterback': 'DeShone Kizer', 'team': 'CLE', 'home_away': '@', 'opponent': 'CHI', 'adjPF': '15.4', 'adjPA': '14.6', 'Proj': '15'},
{'quarterback': 'Mitch Trubisky', 'team': 'CHI', 'home_away': 'vs.', 'opponent': 'CLE', 'adjPF': '11.9', 'adjPA': '22.6', 'Proj': '16.7'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'home_away': '@', 'opponent': 'CIN', 'adjPF': '20.8', 'adjPA': '18.7', 'Proj': '19.8'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'home_away': 'vs.', 'opponent': 'DET', 'adjPF': '16.5', 'adjPA': '18.9', 'Proj': '17.5'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'home_away': '@', 'opponent': 'TEN', 'adjPF': '18', 'adjPA': '19.7', 'Proj': '18.8'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'home_away': 'vs.', 'opponent': 'LAR', 'adjPF': '15.2', 'adjPA': '14.8', 'Proj': '15'},
{'quarterback': 'Jay Cutler', 'team': 'MIA', 'home_away': '@', 'opponent': 'KCC', 'adjPF': '14.1', 'adjPA': '17.8', 'Proj': '15.8'},
{'quarterback': 'Alex Smith', 'team': 'KCC', 'home_away': 'vs.', 'opponent': 'MIA', 'adjPF': '21.7', 'adjPA': '19.2', 'Proj': '20.6'},
{'quarterback': 'Tyrod Taylor', 'team': 'BUF', 'home_away': '@', 'opponent': 'NEP', 'adjPF': '17.1', 'adjPA': '20.3', 'Proj': '18.6'},
{'quarterback': 'Tom Brady', 'team': 'NEP', 'home_away': 'vs.', 'opponent': 'BUF', 'adjPF': '21.5', 'adjPA': '13', 'Proj': '17.7'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'home_away': '@', 'opponent': 'NOS', 'adjPF': '15.6', 'adjPA': '16.2', 'Proj': '15.9'},
{'quarterback': 'Drew Brees', 'team': 'NOS', 'home_away': 'vs.', 'opponent': 'ATL', 'adjPF': '18.9', 'adjPA': '18.5', 'Proj': '18.7'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'home_away': '@', 'opponent': 'NYJ', 'adjPF': '18', 'adjPA': '22.3', 'Proj': '20'},
{'quarterback': 'Bryce Petty', 'team': 'NYJ', 'home_away': 'vs.', 'opponent': 'LAC', 'adjPF': '11.2', 'adjPA': '14', 'Proj': '12.4'},
{'quarterback': 'Brock Osweiler', 'team': 'DEN', 'home_away': '@', 'opponent': 'WAS', 'adjPF': '15.6', 'adjPA': '16.6', 'Proj': '16'},
{'quarterback': 'Kirk Cousins', 'team': 'WAS', 'home_away': 'vs.', 'opponent': 'DEN', 'adjPF': '20.1', 'adjPA': '17.1', 'Proj': '18.7'},
{'quarterback': 'Jameis Winston', 'team': 'TBB', 'home_away': '@', 'opponent': 'CAR', 'adjPF': '19.2', 'adjPA': '17.3', 'Proj': '18.4'},
{'quarterback': 'Cam Newton', 'team': 'CAR', 'home_away': 'vs.', 'opponent': 'TBB', 'adjPF': '21.1', 'adjPA': '19.4', 'Proj': '20.3'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'home_away': '@', 'opponent': 'SFF', 'adjPF': '17.4', 'adjPA': '19.4', 'Proj': '18.3'},
{'quarterback': 'Jimmy Garoppolo', 'team': 'SFF', 'home_away': 'vs.', 'opponent': 'JAC', 'adjPF': '15.1', 'adjPA': '11.4', 'Proj': '13.4'},
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': '@', 'opponent': 'DAL', 'adjPF': '23.7', 'adjPA': '19.4', 'Proj': '21.8'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'SEA', 'adjPF': '18.1', 'adjPA': '16.1', 'Proj': '17.2'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': '@', 'opponent': 'ARI', 'adjPF': '15.3', 'adjPA': '18', 'Proj': '16.5'},
{'quarterback': 'Drew Stanton', 'team': 'ARI', 'home_away': 'vs.', 'opponent': 'NYG', 'adjPF': '13.1', 'adjPA': '20.1', 'Proj': '16.3'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'home_away': '@', 'opponent': 'HOU', 'adjPF': '20.4', 'adjPA': '22.9', 'Proj': '21.5'},
{'quarterback': 'T.J. Yates', 'team': 'HOU', 'home_away': 'vs.', 'opponent': 'PIT', 'adjPF': '17.1', 'adjPA': '15.9', 'Proj': '16.5'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'home_away': '@', 'opponent': 'PHI', 'adjPF': '16.6', 'adjPA': '17.3', 'Proj': '16.9'},
{'quarterback': 'Nick Foles', 'team': 'PHI', 'home_away': 'vs.', 'opponent': 'OAK', 'adjPF': '18.2', 'adjPA': '19.6', 'Proj': '18.8'}
];

var matchups = [
'Jacoby Brissett (IND @ BAL): 14.2 proj. pts.',
'Joe Flacco (BAL vs. IND): 15.8 proj. pts.',
'Case Keenum (MIN @ GBP): 20.3 proj. pts.',
'Brett Hundley (GBP vs. MIN): 14.8 proj. pts.',
'DeShone Kizer (CLE @ CHI): 15 proj. pts.',
'Mitch Trubisky (CHI vs. CLE): 16.7 proj. pts.',
'Matthew Stafford (DET @ CIN): 19.8 proj. pts.',
'Andy Dalton (CIN vs. DET): 17.5 proj. pts.',
'Jared Goff (LAR @ TEN): 18.8 proj. pts.',
'Marcus Mariota (TEN vs. LAR): 15 proj. pts.',
'Jay Cutler (MIA @ KCC): 15.8 proj. pts.',
'Alex Smith (KCC vs. MIA): 20.6 proj. pts.',
'Tyrod Taylor (BUF @ NEP): 18.6 proj. pts.',
'Tom Brady (NEP vs. BUF): 17.7 proj. pts.',
'Matt Ryan (ATL @ NOS): 15.9 proj. pts.',
'Drew Brees (NOS vs. ATL): 18.7 proj. pts.',
'Philip Rivers (LAC @ NYJ): 20 proj. pts.',
'Bryce Petty (NYJ vs. LAC): 12.4 proj. pts.',
'Brock Osweiler (DEN @ WAS): 16 proj. pts.',
'Kirk Cousins (WAS vs. DEN): 18.7 proj. pts.',
'Jameis Winston (TBB @ CAR): 18.4 proj. pts.',
'Cam Newton (CAR vs. TBB): 20.3 proj. pts.',
'Blake Bortles (JAC @ SFF): 18.3 proj. pts.',
'Jimmy Garoppolo (SFF vs. JAC): 13.4 proj. pts.',
'Russell Wilson (SEA @ DAL): 21.8 proj. pts.',
'Dak Prescott (DAL vs. SEA): 17.2 proj. pts.',
'Eli Manning (NYG @ ARI): 16.5 proj. pts.',
'Drew Stanton (ARI vs. NYG): 16.3 proj. pts.',
'Ben Roethlisberger (PIT @ HOU): 21.5 proj. pts.',
'T.J. Yates (HOU vs. PIT): 16.5 proj. pts.',
'Derek Carr (OAK @ PHI): 16.9 proj. pts.',
'Nick Foles (PHI vs. OAK): 18.8 proj. pts.',
]